---
title: "MA678-Midterm-Project"
output: 
  pdf_document: 
    latex_engine: xelatex
author: Fengyuan Shen (Vincent)
date: "2023-12-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

## Introduction

## Method

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(reshape2)
library(lubridate)
library(stringr)
library(kableExtra)
```

```{r echo=FALSE}
# listings <- read.csv("data/listings.csv", header = T)
# calendar <- read.csv("data/calendar.csv", header = T)
# reviews <- read.csv("data/reviews.csv", header = T)
```

```{r echo=FALSE}
# Combine data
file_list <- list.files(path = "listings_data", pattern = "*.csv", full.names = TRUE)
combined_data <- bind_rows(lapply(file_list, read.csv))
write.csv(combined_data, "listings_data/listings.csv", row.names = FALSE)
```

```{r echo=FALSE}
# read csv
listings <- read.csv("data/listings.csv", header = T)
```

### Data Cleaning

```{r echo=FALSE}
listings_data <- listings |> 
  select(id, host_id, host_name, host_since, host_response_time, host_response_rate,
         host_acceptance_rate, host_is_superhost, host_listings_count, 
         host_identity_verified, latitude, longitude, property_type, room_type,
         accommodates, bathrooms_text, bedrooms, beds, price, minimum_nights,
         maximum_nights, number_of_reviews, review_scores_rating, review_scores_accuracy,
         review_scores_cleanliness, review_scores_checkin, review_scores_communication,
         review_scores_location, review_scores_value, instant_bookable)
```

```{r echo=FALSE}
kable(head(listings_data[,c(3,4,16:19,23)]))
```

```{r echo=FALSE}
summary(listings_data)
```

```{r echo=FALSE}
# Price
# Omit missing values
listings_data <- na.omit(listings_data)

# Converts the data format of the Price column
listings_data$price <- as.numeric(str_replace_all(listings_data$price, "[^0-9.]", ""))

# Remove outliers in the Price column
Q1 <- quantile(listings_data$price, 0.25)
Q3 <- quantile(listings_data$price, 0.75)
IQR <- Q3 - Q1
lower_bound <- Q1 - 1.5 * IQR
upper_bound <- Q3 + 1.5 * IQR
listings_data <- listings_data |> filter(price >= lower_bound & price <= upper_bound)
```

```{r echo=FALSE}
# Host response
# Converts categorical variables to numeric types
listings_data <- listings_data |> 
  mutate(host_response_time = case_when(
    host_response_time == "within an hour" ~ 0,
    host_response_time == "within a few hours" ~ 1,
    host_response_time  == "a few days or more" ~ 2,
    TRUE ~ NA  # If neither match, set the column to NA
  )) |> 
  filter(!is.na(host_response_time)) # Filter out rows with NA values
```

```{r echo=FALSE}
# Host is superhost
listings_data <- listings_data |> filter(host_is_superhost %in% c('f','t'))
# Converts categorical variables to numeric types
listings_data$host_is_superhost <- ifelse(listings_data$host_is_superhost == 'f', 0, 1)
```

```{r echo=FALSE}
# Host identify verified
listings_data <- listings_data |> filter(host_identity_verified %in% c('f','t'))
# Converts categorical variables to numeric types
listings_data$host_identity_verified <- ifelse(listings_data$host_identity_verified == 'f',
                                               0, 1)
```

```{r echo=FALSE}
# Instant bookable
listings_data <- listings_data |> filter(instant_bookable %in% c('f','t'))
# Converts categorical variables to numeric types
listings_data$instant_bookable <- ifelse(listings_data$instant_bookable == 'f', 0, 1)
```

```{r echo=FALSE, warning=FALSE}
# Converts a percentage string to a numeric type
listings_data$host_response_rate <- 
  as.numeric(sub("%", "", listings_data$host_response_rate)) / 100
listings_data$host_acceptance_rate <- 
  as.numeric(sub("%", "", listings_data$host_acceptance_rate)) / 100
listings_data <- drop_na(listings_data, host_response_rate, host_acceptance_rate)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# write.csv(listings_data, "listings_data.csv")
```

### EDA

```{r}
# Heatmap

# 选择数值型列进行相关性分析
numeric_data <- data[sapply(data, is.numeric)]

# 计算相关矩阵
correlation_matrix <- cor(numeric_data, use="complete.obs")

# 绘制热图
melted_correlation <- melt(correlation_matrix)
ggplot(data = melted_correlation, aes(Var1, Var2, fill = value)) +
    geom_tile() +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                         midpoint = 0, limit = c(-1,1)) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(title = "Correlation Matrix of Selected Variables", x = '', y = '')
```

```{r}
# 数据可视化

# 地理位置与价格关系散点图
ggplot(cleaned_data, aes(x=longitude, y=latitude, color=price)) +
  geom_point(alpha=0.5) +
  scale_color_gradient(low="blue", high="red") +
  theme_minimal() +
  labs(title="Geographic Location vs. Price of Airbnb Listings in Los Angeles",
       x="Longitude", y="Latitude")
```

```{r}
# 房源类型分布条形图
# 确保数据集中存在 'room_type' 列
if ("room_type" %in% names(cleaned_data)) {
  ggplot(cleaned_data, aes(x=room_type)) +
    geom_bar() +
    theme_minimal() +
    labs(title="Distribution of Room Types in Airbnb Listings",
         x="Room Type", y="Number of Listings")
}
```

```{r}
# 多变量分析
# 选择适合多变量分析的列
variables_for_pairplot <- c("price", "latitude", "longitude", "number_of_reviews", "review_scores_rating")
cleaned_data %>%
  select(all_of(variables_for_pairplot)) %>%
  drop_na() %>%
  GGally::ggpairs()
```

### Fitting Model

#### Model1: Linear Regression

## Result

## Discussion

## Appendix
